version: '{branch}-{build}'
build: off

image:
  - Visual Studio 2019

platform:
  - x86
  - x64

environment:
  global:
    PYTHONUNBUFFERED: 'True'
    PYTHONWARNINGS: 'ignore:::wheel.pep425tags:'
    CODECOV_ENV: PYTHON_VERSION, PLATFORM

  matrix:
    - PYTHON_VERSION: 3.9
    - PYTHON_VERSION: 3.8
    - PYTHON_VERSION: 3.7
    - PYTHON_VERSION: 3.6
    - PYTHON_VERSION: 3.9
      PYTHONNET_SHUTDOWN_MODE: Soft
    - PYTHON_VERSION: 3.8
      PYTHONNET_SHUTDOWN_MODE: Soft
    - PYTHON_VERSION: 3.7
      PYTHONNET_SHUTDOWN_MODE: Soft
    - PYTHON_VERSION: 3.6
      PYTHONNET_SHUTDOWN_MODE: Soft
init:
  # Update Environment Variables based on matrix/platform
  - set PY_VER=%PYTHON_VERSION:.=%
  - set PYTHON=C:\PYTHON%PY_VER%
  - if %PLATFORM%==x64 (set PYTHON=%PYTHON%-x64)
  - set PYTHONNET_PYDLL=%PYTHON%\python%PY_VER%.dll

  # Put desired Python version first in PATH
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - python -m pip install -U pip
  - pip install --upgrade -r requirements.txt --quiet

build_script:
  # Create clean `sdist`. Only used for releases
  - python setup.py --quiet sdist
  - python setup.py bdist_wheel

test_script:
  - pip install --no-index --find-links=.\dist\ pythonnet
  #- ps: .\ci\appveyor_run_tests.ps1
  - pytest
  - dotnet test src/embed_tests/

artifacts:
  - path: dist\*
